# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Tags Region

africa = Tag.create(category: 0, father: nil, tag: 'Afrika')
Tag.create(category: 0, father: africa.id, tag: 'Marokko')
Tag.create(category: 0, father: africa.id, tag: 'Südafrika')
Tag.create(category: 0, father: africa.id, tag: 'Ägypten')
america = Tag.create(category: 0, father: nil, tag: 'Amerika')
Tag.create(category: 0, father: america.id, tag: 'Latein Amerika')
Tag.create(category: 0, father: america.id, tag: 'Mexico')
Tag.create(category: 0, father: america.id, tag: 'USA & Kanada')
asia = Tag.create(category: 0, father: nil, tag: 'Asien')
Tag.create(category: 0, father: asia.id, tag: 'China')
Tag.create(category: 0, father: asia.id, tag: 'Indien')
Tag.create(category: 0, father: asia.id, tag: 'Japan')
Tag.create(category: 0, father: asia.id, tag: 'Korea')
Tag.create(category: 0, father: asia.id, tag: 'Thailand')
Tag.create(category: 0, father: asia.id, tag: 'Vietnam')
Tag.create(category: 0, father: nil, tag: 'Australien')
europe = Tag.create(category: 0, father: nil, tag: 'Europa')
Tag.create(category: 0, father: europe.id, tag: 'Belgien')
Tag.create(category: 0, father: europe.id, tag: 'Deutschland')
Tag.create(category: 0, father: europe.id, tag: 'Dänemark')
Tag.create(category: 0, father: europe.id, tag: 'Finnland')
Tag.create(category: 0, father: europe.id, tag: 'Frankreich')
Tag.create(category: 0, father: europe.id, tag: 'Griechenland')
Tag.create(category: 0, father: europe.id, tag: 'Großbritannien & Irland')
Tag.create(category: 0, father: europe.id, tag: 'Italien')
Tag.create(category: 0, father: europe.id, tag: 'Luxemburg')
Tag.create(category: 0, father: europe.id, tag: 'Malta')
Tag.create(category: 0, father: europe.id, tag: 'Niederlande')
Tag.create(category: 0, father: europe.id, tag: 'Norwegen')
Tag.create(category: 0, father: europe.id, tag: 'Polen')
Tag.create(category: 0, father: europe.id, tag: 'Portugal')
Tag.create(category: 0, father: europe.id, tag: 'Russland')
Tag.create(category: 0, father: europe.id, tag: 'Schweden')
Tag.create(category: 0, father: europe.id, tag: 'Schweiz')
Tag.create(category: 0, father: europe.id, tag: 'Spanien')
Tag.create(category: 0, father: europe.id, tag: 'Tschechien')
Tag.create(category: 0, father: europe.id, tag: 'Türkei')
Tag.create(category: 0, father: europe.id, tag: 'Ungarn')
Tag.create(category: 0, father: europe.id, tag: 'Weißrussland')
Tag.create(category: 0, father: europe.id, tag: 'Österreich')
Tag.create(category: 0, father: nil, tag: 'Karibik & Exotik')
Tag.create(category: 0, father: nil, tag: 'Mittlerer und Naher Osten')
Tag.create(category: 0, father: nil, tag: 'Osteuropa')

# Tags Kategorie
# Baking
Tag.create(category: 1, father: nil, tag: 'Süßspeisen')
Tag.create(category: 1, father: nil, tag: 'Brot')
Tag.create(category: 1, father: nil, tag: 'Cremes')
Tag.create(category: 1, father: nil, tag: 'Eis')
Tag.create(category: 1, father: nil, tag: 'Plätzchen')
Tag.create(category: 1, father: nil, tag: 'Kuchen')
Tag.create(category: 1, father: nil, tag: 'Tarte/Quiche')
Tag.create(category: 1, father: nil, tag: 'Torten ')

# Drink
beverage = Tag.create(category: 1, father: nil, tag: 'Getränke')
Tag.create(category: 1, father: beverage, tag: 'Bowle')
beverage_cocktail = Tag.create(category: 1, father: beverage.id, tag: 'Cocktail')
Tag.create(category: 1, father: beverage_cocktail.id, tag: 'Alkoholfrei')
Tag.create(category: 1, father: beverage.id, tag: 'Kaffee, Tee & Kakao')
Tag.create(category: 1, father: beverage.id, tag: 'Likör')
Tag.create(category: 1, father: beverage.id, tag: 'Punsch')
Tag.create(category: 1, father: beverage.id, tag: 'Shake')
Tag.create(category: 1, father: beverage.id, tag: 'Smoothie')

# Course
Tag.create(category: 1, father: nil, tag: 'Hauptspeise')
Tag.create(category: 1, father: nil, tag: 'Nachspeise')
Tag.create(category: 1, father: nil, tag: 'Vorspeise')
Tag.create(category: 1, father: nil, tag: 'Frühstück')
Tag.create(category: 1, father: nil, tag: 'Mittagessen')
Tag.create(category: 1, father: nil, tag: 'Abendessen')
Tag.create(category: 1, father: nil, tag: 'Snack')
Tag.create(category: 1, father: nil, tag: 'Kalt')
Tag.create(category: 1, father: nil, tag: 'Warm ')
Tag.create(category: 1, father: nil, tag: 'Beilage')

# Ingredient Categorized
Tag.create(category: 1, father: nil, tag: 'Gemüse')
Tag.create(category: 1, father: nil, tag: 'Hülsenfrüchte')
Tag.create(category: 1, father: nil, tag: 'Klöße')
Tag.create(category: 1, father: nil, tag: 'Reis/Getreide')
Tag.create(category: 1, father: nil, tag: 'Fisch')
poultry = Tag.create(category: 1, father: nil, tag: 'Geflügel')
Tag.create(category: 1, father: poultry.id, tag: 'Wildgeflügel')
Tag.create(category: 1, father: nil, tag: 'Innereien')
Tag.create(category: 1, father: nil, tag: 'Krustentier & Muscheln')
Tag.create(category: 1, father: nil, tag: 'Lamm & Ziege')
Tag.create(category: 1, father: nil, tag: 'Pasta & Nudel')
Tag.create(category: 1, father: nil, tag: 'Pilze')
Tag.create(category: 1, father: nil, tag: 'Rind')
Tag.create(category: 1, father: nil, tag: 'Schwein')
Tag.create(category: 1, father: nil, tag: 'Wild & Kaninchen')
Tag.create(category: 1, father: nil, tag: 'Salat')
Tag.create(category: 1, father: nil, tag: 'Eier & Käse')
Tag.create(category: 1, father: nil, tag: 'Fleisch & Wurst')
Tag.create(category: 1, father: nil, tag: 'Früchte')
Tag.create(category: 1, father: nil, tag: 'Tapas')

# Miscellaneous
Tag.create(category: 1, father: nil, tag: 'Dressing')
Tag.create(category: 1, father: nil, tag: 'Suppe')
Tag.create(category: 1, father: nil, tag: 'Sauce')
Tag.create(category: 1, father: nil, tag: 'Aufstrich')

# Method
Tag.create(category: 1, father: nil, tag: 'Backen')
Tag.create(category: 1, father: nil, tag: 'Gewürze/Öl/Essig/Pasten')
Tag.create(category: 1, father: nil, tag: 'Grundrezepte')
Tag.create(category: 1, father: nil, tag: 'Haltbarmachen')
Tag.create(category: 1, father: nil, tag: 'Auflauf')
Tag.create(category: 1, father: nil, tag: 'Barbecue & Grill')
Tag.create(category: 1, father: nil, tag: 'Blanchieren')
Tag.create(category: 1, father: nil, tag: 'Braten')
Tag.create(category: 1, father: nil, tag: 'Dünsten')
Tag.create(category: 1, father: nil, tag: 'Flambieren')
Tag.create(category: 1, father: nil, tag: 'Fondue')
Tag.create(category: 1, father: nil, tag: 'Frittieren')
Tag.create(category: 1, father: nil, tag: 'Kochen')
Tag.create(category: 1, father: nil, tag: 'Marinieren')
Tag.create(category: 1, father: nil, tag: 'Mikrowelle')
Tag.create(category: 1, father: nil, tag: 'Römertopf')
Tag.create(category: 1, father: nil, tag: 'Schmoren')
Tag.create(category: 1, father: nil, tag: 'Wok')
Tag.create(category: 1, father: nil, tag: 'Überbacken')
Tag.create(category: 1, father: nil, tag: 'Eintopf')

# Units
Unit.create(name: '')
Unit.create(name: 'g')
Unit.create(name: 'ml')
Unit.create(name: 'EL')
Unit.create(name: 'TL')
Unit.create(name: 'Msp')
Unit.create(name: 'Scheibe(n)')
Unit.create(name: 'Dose(n)')
Unit.create(name: 'Tube(n)')
Unit.create(name: 'Packung')
Unit.create(name: 'Bund')
Unit.create(name: 'große')
Unit.create(name: 'mittlere')
Unit.create(name: 'kleine')
